name: Build And Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            - name: Build
              run: |
                make build
            - name: Publish
              env:
                TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: |
                make publish
            - name: Cleanup
              run: |
                make clean

