name: Podcast data

on:
  push:
    branches:
      - main

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Build
              run: |
                make build
            # - name: Publish
            #   run: |
            #     make publish
